language: node_js
node_js:
  - "io.js"
before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
script: npm run-script coveralls
after_script: codeclimate < coverage/**/lcov.info
